import SwiftUI

/// Manages multi-language support (English and Turkish) for WristArcade.
/// Automatically detects phone/system language and allows user override in settings.
public final class LocalizationManager: ObservableObject {
    public static let shared = LocalizationManager()
    
    @AppStorage("app_language") public var selectedLanguage: String = "auto" {
        didSet {
            objectWillChange.send()
        }
    }
    
    /// Resolves the actual language code ("en" or "tr")
    public var currentLanguage: String {
        if selectedLanguage == "tr" { return "tr" }
        if selectedLanguage == "en" { return "en" }
        
        // Auto mode: check system locale
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? ""
        if preferred.starts(with: "tr") {
            return "tr"
        }
        return "en"
    }
    
    public var isTurkish: Bool {
        return currentLanguage == "tr"
    }
    
    /// Returns the localized string for a given key
    public func t(_ key: String) -> String {
        let lang = currentLanguage
        if let dict = strings[lang], let val = dict[key] {
            return val
        }
        // Fallback to English
        if let dict = strings["en"], let val = dict[key] {
            return val
        }
        return key
    }
    
    private init() {}
    
    // Comprehensive dictionary for all UI text, settings, dialogs, and game instructions
    private let strings: [String: [String: String]] = [
        "en": [
            // General & App
            "app_title": "WristArcade",
            "app_tagline": "The Ultimate Watch Game Collection",
            "unlock_banner_title": "UNLOCK ALL 60 GAMES",
            "unlock_banner_subtitle": "Cards • Crown • Reflex • Puzzle • No Ads",
            "free_tag": "FREE",
            "pro_tag": "PRO",
            "restore_purchases": "Restore Purchases",
            "pro_activated": "PRO UNLOCKED",
            "version_info": "WristArcade v2.2 • 100% Legal & Offline",
            "daily_pro_free": "FREE TODAY",
            "daily_pro_desc": "Daily Free Pro Game Pass",
            "fitness_title": "Fitness Quest",
            "fitness_steps": "Daily Steps",
            "claim_xp": "Claim +100 XP",
            "theme_label": "Display Theme",
            "motion_tilt": "Wrist Tilt (Motion)",
            "motion_sensitivity": "Tilt Sensitivity",
            
            // Categories & Filters
            "filter_all": "All",
            "cat_cards": "Card Games",
            "cat_crown": "Crown Arcades",
            "cat_reflex": "Speed & Reflex",
            "cat_puzzle": "Puzzle & Strategy",
            "trophies": "Trophies",
            
            // Settings
            "settings_title": "Settings",
            "preferences": "PREFERENCES",
            "language_label": "Language",
            "lang_auto": "System (Auto)",
            "lang_en": "English",
            "lang_tr": "Türkçe",
            "haptic_feedback": "Haptic Feedback",
            "sound_effects": "Sound Effects",
            "data_stats": "DATA & STATS",
            "total_sessions": "Total Sessions",
            "reset_scores": "Reset High Scores",
            "reset_confirm_title": "Reset High Scores?",
            "reset_confirm_msg": "This will clear all personal best records.",
            "reset_btn": "Reset All",
            "cancel": "Cancel",
            "done": "Done",
            "close": "Close",
            "got_it": "Got it!",
            "how_to_play": "How to Play",
            "objective": "Objective",
            "controls": "Controls",
            "pro_tips": "Pro Tips",
            
            // Score & State
            "high_score": "High Score",
            "score": "Score",
            "best": "Best",
            "level": "Level",
            "time": "Time",
            "moves": "Moves",
            "game_over": "GAME OVER",
            "you_win": "YOU WIN!",
            "tap_to_restart": "Tap to Play Again",
            "next_target": "Next",
            
            // Paywall
            "paywall_title": "WristArcade PRO",
            "paywall_subtitle": "Unlock the full 46-game collection forever with a single purchase.",
            "paywall_feature_1": "All 34 Pro Games Unlocked",
            "paywall_feature_2": "Poker, Dice, Roulette, Baccarat & More",
            "paywall_feature_3": "Crown Haptics, Chess & Maze Muncher",
            "paywall_feature_4": "No Ads, No Subscriptions, Offline",
            "paywall_buy_button": "Unlock Forever for",
            
            // Game Titles
            "title_blackjack": "Classic 21",
            "sub_blackjack": "Arcade Blackjack",
            "title_videopoker": "Video Poker",
            "sub_videopoker": "Jacks or Better",
            "title_microsolitaire": "Micro Solitaire",
            "sub_microsolitaire": "Golf Card Clear",
            "title_cardwar": "Card War",
            "sub_cardwar": "High Card Battle",
            "title_cardpairs": "Card Pairs",
            "sub_cardpairs": "Memory Match",
            "title_highlow": "High-Low",
            "sub_highlow": "Card Guess Streak",
            "title_luckydice": "Lucky Dice",
            "sub_luckydice": "Roll & Hold Combos",
            "title_luckyroulette": "Lucky Roulette",
            "sub_luckyroulette": "Spin & Bet Table",
            "title_baccarat": "Baccarat Mini",
            "sub_baccarat": "Punto Banco 9s",
            "title_triplepoker": "Three Card Poker",
            "sub_triplepoker": "Fast Showdown",
            
            "title_paddle": "Crown Paddle",
            "sub_paddle": "Wall Tennis",
            "title_snake": "Crown Snake",
            "sub_snake": "Classic Nibbler",
            "title_safecracker": "Safe Cracker",
            "sub_safecracker": "Haptic Crown Lock",
            "title_crownrunner": "Crown Runner",
            "sub_crownrunner": "Infinite Hop",
            "title_spaceevade": "Space Evade",
            "sub_spaceevade": "Star Collector",
            "title_brickcrusher": "Brick Crusher",
            "sub_brickcrusher": "Smash Blocks",
            "title_galaxydefender": "Galaxy Defender",
            "sub_galaxydefender": "Crown Plasma Defense",
            "title_deepreel": "Deep Sea Reel",
            "sub_deepreel": "Crown Trophy Fishing",
            "title_crownmaze": "Crown Maze",
            "sub_crownmaze": "Gyro Labyrinth",
            "title_subdive": "Submarine Dive",
            "sub_subdive": "Depth & Torpedo",
            
            "title_speednumbers": "Speed Tap 1-9",
            "sub_speednumbers": "Schulte Number Rush",
            "title_wingflap": "Wing Flap",
            "sub_wingflap": "Tap to Fly",
            "title_reflextap": "Reflex Tap",
            "sub_reflextap": "Speed Reaction Test",
            "title_whackmole": "Whack-A-Dot",
            "sub_whackmole": "Pop-up Reflex",
            "title_colormemory": "Color Sequence",
            "sub_colormemory": "Simon Reflex",
            "title_mathblitz": "Math Blitz",
            "sub_mathblitz": "Rapid Mental Math",
            "title_towerstack": "Tower Stacker",
            "sub_towerstack": "Neon Block Heights",
            "title_highwayracer": "Highway Racer",
            "sub_highwayracer": "Neon Traffic Weave",
            "title_neonbeat": "Neon Beat",
            "sub_neonbeat": "Dual-Lane Rhythm",
            "title_quickdraw": "Quick Draw Duel",
            "sub_quickdraw": "Western Reflex",
            
            "title_merge2048": "Number Merge",
            "sub_merge2048": "2048 Tile Puzzle",
            "title_numberslide": "Number Slide",
            "sub_numberslide": "3x3 8-Puzzle",
            "title_wordguess": "Word Guess",
            "sub_wordguess": "4-Letter Deduction",
            "title_blockfall": "Color Blocks",
            "sub_blockfall": "Falling 3-Match",
            "title_mines": "Mine Grid",
            "sub_mines": "Tactical Sweeper",
            "title_tictactoe": "Tic-Tac-Toe",
            "sub_tictactoe": "Smart AI & 2-Player",
            "title_memorymatrix": "Memory Matrix",
            "sub_memorymatrix": "Chimp Memory Test",
            "title_bullseyearchery": "Bullseye Archery",
            "sub_bullseyearchery": "Wind Physics Target",
            "title_pipeconnect": "Pipe Connect",
            "sub_pipeconnect": "Rotate Flow Puzzle",
            "title_lasermirror": "Laser Mirror",
            "sub_lasermirror": "Optic Beam Prism",
            "title_pisti": "Pisti Card Match",
            "sub_pisti": "Classic Turkish Deck",
            "title_klondikesolitaire": "Klondike Solitaire",
            "sub_klondikesolitaire": "7-Column Classic",
            "title_mazemuncher": "Maze Muncher",
            "sub_mazemuncher": "Neon Dot Chomp",
            "title_chess": "Mini Chess",
            "sub_chess": "Tactical Board AI",
            "title_checkers": "Classic Checkers",
            "sub_checkers": "Jump & Crown Board",
            "title_slidingblocks": "Sliding Blocks",
            "sub_slidingblocks": "Block Escape Puzzle",
            "title_airhockey": "Air Hockey",
            "sub_airhockey": "Neon Puck Battle",
            "title_hangman": "Hangman",
            "sub_hangman": "Word Deduction",
            "title_minisudoku": "Mini Sudoku",
            "sub_minisudoku": "4x4 Number Grid",
            "title_lunarlander": "Lunar Lander",
            "sub_lunarlander": "Moon Descent Physics",
            "title_ninemensmorris": "Nine Men's Morris",
            "sub_ninemensmorris": "Ancient Tactical Mill",
            "title_seabattle": "Sea Battle",
            "sub_seabattle": "Battleship Sonar Radar",
            "title_reversi": "Reversi",
            "sub_reversi": "Classic Othello Flip",
            "title_word5": "Word Master",
            "sub_word5": "5-Letter Word Hunt",
            "title_darts": "Precision Darts",
            "sub_darts": "Target Dial Throw",
            "title_microcircuit": "Micro Circuit",
            "sub_microcircuit": "Drift & Crown Racer",
            "title_bombdefusal": "Bomb Defusal",
            "sub_bombdefusal": "Logic Wire Cutter",
            "title_target24": "24 Solver",
            "sub_target24": "4-Number Target Math",
            "title_tabletennis": "Air Tennis",
            "sub_tabletennis": "Retro Court Spin",
            "title_duel21": "21 Duel",
            "sub_duel21": "2-Player Pass & Play"
        ],
        "tr": [
            // General & App
            "app_title": "WristArcade",
            "app_tagline": "Apple Watch İçin Mega Oyun Koleksiyonu",
            "unlock_banner_title": "TÜM 60 OYUNUN KİLİDİNİ AÇ",
            "unlock_banner_subtitle": "Kartlar • Crown • Refleks • Bulmaca • Reklamsız",
            "free_tag": "ÜCRETSİZ",
            "pro_tag": "PRO",
            "restore_purchases": "Satın Alımları Geri Yükle",
            "pro_activated": "PRO AKTİF",
            "version_info": "WristArcade v2.2 • %100 Telifsiz ve Yasal",
            "daily_pro_free": "BUGÜN ÜCRETSİZ",
            "daily_pro_desc": "Günün Ücretsiz Pro Oyunu",
            "fitness_title": "Aktivite Görevi",
            "fitness_steps": "Günlük Adım",
            "claim_xp": "+100 XP Al",
            "theme_label": "Ekran Teması",
            "motion_tilt": "Bilek Hareketi (Jiroskop)",
            "motion_sensitivity": "Eğim Hassasiyeti",
            
            // Categories & Filters
            "filter_all": "Tümü",
            "cat_cards": "Kart Oyunları",
            "cat_crown": "Crown Klasikleri",
            "cat_reflex": "Hız & Refleks",
            "cat_puzzle": "Zeka & Strateji",
            "trophies": "Kupalar",
            
            // Settings
            "settings_title": "Ayarlar",
            "preferences": "TERCİHLER",
            "language_label": "Dil (Language)",
            "lang_auto": "Sistem Dili (Otomatik)",
            "lang_en": "English (İngilizce)",
            "lang_tr": "Türkçe",
            "haptic_feedback": "Dokunsal Titreşim (Haptic)",
            "sound_effects": "Ses Efektleri",
            "data_stats": "VERİLER & İSTATİSTİKLER",
            "total_sessions": "Toplam Oynama",
            "reset_scores": "Rekorları Sıfırla",
            "reset_confirm_title": "Rekorlar Sıfırlansın mı?",
            "reset_confirm_msg": "Bu işlem tüm oyunlardaki en yüksek skorlarınızı silecektir.",
            "reset_btn": "Tümünü Sıfırla",
            "cancel": "Vazgeç",
            "done": "Tamam",
            "close": "Kapat",
            "got_it": "Anladım!",
            "how_to_play": "Nasıl Oynanır?",
            "objective": "Hedef",
            "controls": "Kontroller",
            "pro_tips": "Püf Noktası",
            
            // Score & State
            "high_score": "Rekor",
            "score": "Skor",
            "best": "En İyi",
            "level": "Seviye",
            "time": "Süre",
            "moves": "Hamle",
            "game_over": "OYUN BİTTİ",
            "you_win": "KAZANDIN!",
            "tap_to_restart": "Tekrar Oynamak İçin Dokun",
            "next_target": "Sıradaki",
            
            // Paywall
            "paywall_title": "WristArcade PRO",
            "paywall_subtitle": "Tek bir satın alımla 46 oyunluk devasa koleksiyonun kilidini sonsuza dek açın.",
            "paywall_feature_1": "34 Pro Oyunun Tamamı Açık",
            "paywall_feature_2": "Poker, Zarlar, Rulet, Bakara & Daha Fazlası",
            "paywall_feature_3": "Crown Haptik Kasa, Satranç & Labirent Yemcisi",
            "paywall_feature_4": "Reklamsız, Aboneliksiz, Çevrimdışı",
            "paywall_buy_button": "Ömür Boyu Aç:",
            
            // Game Titles
            "title_blackjack": "Classic 21",
            "sub_blackjack": "Arcade Blackjack",
            "title_videopoker": "Video Poker",
            "sub_videopoker": "Jacks or Better",
            "title_microsolitaire": "Micro Solitaire",
            "sub_microsolitaire": "Golf Kart Temizleme",
            "title_cardwar": "Kart Savaşı",
            "sub_cardwar": "Yüksek Kart Mücadelesi",
            "title_cardpairs": "Kart Eşleştirme",
            "sub_cardpairs": "Hafıza Kartları",
            "title_highlow": "High-Low",
            "sub_highlow": "Kart Tahmin Serisi",
            "title_luckydice": "Şanslı Zarlar",
            "sub_luckydice": "Zar Kombinasyonları",
            "title_luckyroulette": "Şanslı Rulet",
            "sub_luckyroulette": "Çark Çevir & Bahis Yap",
            "title_baccarat": "Mini Baccarat",
            "sub_baccarat": "Punto Banco 9'lar",
            "title_triplepoker": "Üç Kart Poker",
            "sub_triplepoker": "Hızlı Kart Düellosu",
            
            "title_paddle": "Crown Paddle",
            "sub_paddle": "Duvar Tenisi",
            "title_snake": "Crown Snake",
            "sub_snake": "Klasik Yılan",
            "title_safecracker": "Kasa Hırsızı",
            "sub_safecracker": "Crown Haptik Kilit",
            "title_crownrunner": "Crown Runner",
            "sub_crownrunner": "Sonsuz Zıplama",
            "title_spaceevade": "Uzay Kaçışı",
            "sub_spaceevade": "Yıldız Toplayıcı",
            "title_brickcrusher": "Tuğla Kırma",
            "sub_brickcrusher": "Renkli Tuğlalar",
            "title_galaxydefender": "Galaksi Savunması",
            "sub_galaxydefender": "Crown Uzay Tareti",
            "title_deepreel": "Derin Olta",
            "sub_deepreel": "Crown Trofe Balıkçılık",
            "title_crownmaze": "Döner Labirent",
            "sub_crownmaze": "Dönen Jiroskop Labirenti",
            "title_subdive": "Denizaltı Dalışı",
            "sub_subdive": "Crown Derinlik & Mayınlar",
            
            "title_speednumbers": "Hızlı 1-9",
            "sub_speednumbers": "Karma Tablo Sıralama",
            "title_wingflap": "Kanat Çırpma",
            "sub_wingflap": "Dokunarak Uç",
            "title_reflextap": "Refleks Testi",
            "sub_reflextap": "Milisaniye Hız Ölçer",
            "title_whackmole": "Hedef Dokunmaca",
            "sub_whackmole": "Anlık Hedef Refleksi",
            "title_colormemory": "Renk Sırası",
            "sub_colormemory": "Simon Hafıza Ritmi",
            "title_mathblitz": "Hızlı Matematik",
            "sub_mathblitz": "3 Saniyede Zihin Matı",
            "title_towerstack": "Denge Kulesi",
            "sub_towerstack": "Neon Kat Çıkma",
            "title_highwayracer": "Otoyol Yarışçısı",
            "sub_highwayracer": "Neon Trafik Kaçışı",
            "title_neonbeat": "Neon Ritim",
            "sub_neonbeat": "Çift Şerit Ritim Vuruşu",
            "title_quickdraw": "Kovboy Düello",
            "sub_quickdraw": "Vahşi Batı Refleks",
            
            "title_merge2048": "Sayı Birleştir",
            "sub_merge2048": "2048 Blok Bulmacası",
            "title_numberslide": "Rakam Kaydırma",
            "sub_numberslide": "3x3 8-Puzzle",
            "title_wordguess": "Kelime Tahmini",
            "sub_wordguess": "4 Harfli Gizem",
            "title_blockfall": "Renk Blokları",
            "sub_blockfall": "Düşen 3'lü Eşleştirme",
            "title_mines": "Mayın Tarlası",
            "sub_mines": "Taktik Mayın Arama",
            "title_tictactoe": "Tic-Tac-Toe",
            "sub_tictactoe": "Akıllı YZ & 2 Kişilik",
            "title_memorymatrix": "Hafıza Matrisi",
            "sub_memorymatrix": "Maymun Testi",
            "title_bullseyearchery": "Hedef Okçuluk",
            "sub_bullseyearchery": "Rüzgar Fiziği Hedefi",
            "title_pipeconnect": "Boru Bağlama",
            "sub_pipeconnect": "Akış Döndürme Bulmacası",
            "title_lasermirror": "Lazer Aynası",
            "sub_lasermirror": "Optik Işın Prizması",
            "title_pisti": "Pişti",
            "sub_pisti": "Geleneksel Türk Kartı",
            "title_klondikesolitaire": "Klasik Soliter",
            "sub_klondikesolitaire": "7 Sütunlu Klondike",
            "title_mazemuncher": "Labirent Yemcisi",
            "sub_mazemuncher": "Neon Yem Toplama",
            "title_chess": "Satranç",
            "sub_chess": "Taktik Zeka Hamleleri",
            "title_checkers": "Klasik Dama",
            "sub_checkers": "Çapraz Taş Yeme",
            "title_slidingblocks": "Kayıcı Bloklar",
            "sub_slidingblocks": "Blok Kaçış Bulmacası",
            "title_airhockey": "Hava Hokeyi",
            "sub_airhockey": "Neon Disk Düellosu",
            "title_hangman": "Adam Asmaca",
            "sub_hangman": "Kelime Tahmini",
            "title_minisudoku": "Mini Sudoku",
            "sub_minisudoku": "4x4 Sayı Bulmacası",
            "title_lunarlander": "Ay Modülü",
            "sub_lunarlander": "Ay İniş Fiziği",
            "title_ninemensmorris": "9 Taş (Dokuz Taş)",
            "sub_ninemensmorris": "Antik Değirmen Oyunu",
            "title_seabattle": "Amiral Battı",
            "sub_seabattle": "Taktik Radar & Torpido",
            "title_reversi": "Reversi",
            "sub_reversi": "Taş Çevirme Stratejisi",
            "title_word5": "Kelime Ustası",
            "sub_word5": "5 Harfli Gizli Kelime",
            "title_darts": "Dart",
            "sub_darts": "Hedef Tahtası & Crown",
            "title_microcircuit": "Mikro Pist",
            "sub_microcircuit": "Drift & Crown Yarışı",
            "title_bombdefusal": "Bomba İmha",
            "sub_bombdefusal": "Kablo Kesme Mantığı",
            "title_target24": "Hedef 24",
            "sub_target24": "4 Rakamla 24 Bulmacası",
            "title_tabletennis": "Masa Tenisi",
            "sub_tabletennis": "Retro Falso & Fiziği",
            "title_duel21": "21 Düellosu",
            "sub_duel21": "2 Kişilik Blackjack"
        ],
    ]
}

/// Helper function to access localized strings quickly
public func tr(_ key: String) -> String {
    return LocalizationManager.shared.t(key)
}
